### PR TITLE
adapt to coq #10215

### PR DESCRIPTION
**Pull request by gares**
please don't merge yet

### CODE REVIEW

**Comment by gares** [comment]
please merge

**Comment by ejgallego** [comment]
@liyishuai @Lysxia , I have other solution in mind, but for now it seems people is using in the CI the `--ignore-constraints-on=` for the problematic packages; as this specific to CI is not so bad.

**Comment by ejgallego** [comment]
opam seems to be working , let's see :crossed_fingers:

**Comment by liyishuai** [comment]
Fixed Dune build but broke everything else...

**Comment by ejgallego** [comment]
Umm, I have no idea; maybe the correct Coq version is not forced anymore, so the script should do explicitly `opam install coq.dev` ?

**Comment by liyishuai** [comment]
The failing builds also have `coq.dev` installed.

**Comment by ejgallego** [comment]
> The failing builds also have `coq.dev` installed.

That's bizarre.

**Comment by gares** [comment]
I don't even get why CI shows 3 jobs while the travis file has only two in the matrix.
Can someone restart CI?

**Comment by liyishuai** [comment]
#151 has added a job that builds with Dune.

**Comment by SkySkimmer** [comment]
Can we get this merged and let you figure out your CI problems independently?

**Comment by liyishuai** [comment]
I'm trying to [allow failure](https://docs.travis-ci.com/user/customizing-the-build#matching-jobs-with-allow_failures) in Dune build, but didn't find a right config to do so. If someone knows how, feel free to force-push and drop 2622a2ad9b4f2e1e80b455b7dc506af02c571732. Otherwise I'll merge as is.

**Pull request merged**
