### PR TITLE
Adapt to Coq's PR #7797 (removal of reference).

### PR DESCRIPTION
**Pull request by maximedenes**
This is in preparation, the Coq PR hasn't been merged yet.

### CODE REVIEW

**Comment by maximedenes** [comment]
The Coq PR has been merged, can you merge this one? Thanks!

**Comment by lemonidas** [comment]
@liyishuai could you check why the CI test fails? Maybe something needs to be updated before we merge this?

**Comment by liyishuai** [comment]
I think it's Travis CI itself that messed up. Restarting CI.

**Comment by lemonidas** [comment]
Still fails. This CI should be using the dev version of Coq.

**Comment by liyishuai** [comment]
`coq-ext-lib` doesn't support `coq.dev`: coq/opam-coq-archive#361

**Comment by Zimmi48** [comment]
Your CI setup is problematic indeed if the branch master that is supposed to track Coq master branch isn't tested with Coq master. BTW this info in the README looks incorrect: https://github.com/QuickChick/QuickChick#current-release-dependencies. In the meantime, you can trust that this branch is a correct adaptation because it was tested on our side (cf. https://github.com/coq/coq/pull/7797/files#diff-5dae8650f5a95a35b973f7f3cf376db7 and https://gitlab.com/coq/coq/pipelines/24076807).

**Comment by liyishuai** [comment]
Shall we merge `8.8` to `master` before they start to diverge?

**Comment by Zimmi48** [comment]
That's probably sensible, as long as you run CI tests whenever you do such a merge to ensure that none of the newly introduced changes are using a part of the API that was removed or something like this.

**Comment by liyishuai** [comment]
I suppose the task list would be:
1. Merge #82 to `master`
2. Merge `master` to this branch
3. Make sure CI passes
4. Merge this branch back to `master`

**Pull request merged**
