### PR TITLE
Fix for deriving DecOpt when index of inductive is from an inductive family

### PR DESCRIPTION
**Pull request by jaccokrijnen**
This is the same fix as in https://github.com/QuickChick/QuickChick/pull/314 but applied on `master` (and I squashed the two commits that introduced changes). Please see that PR for more details.

### CODE REVIEW

**Review by liyishuai — APPROVED** [review]
Maybe worth adding an example in [`test/plugin/plugin.v`](https://github.com/Xiving/QuickChick/blob/fix-deriving-mutual-inductive/test/plugin/plugin.v) ?

**Comment by lemonidas** [comment]
The current checker-deriving algorithm implementation doesn't handle true mutually inductive datatypes as that would require mutually inductive typeclass instancess. I'm curious what examples this fix enables - a test/example like @liyishuai asked could help here.

**Comment by jaccokrijnen** [comment]
Indeed, this does not implement deriving checkers for mutual inductives. Instead, it fixes a bug where a non-mutual inductive is _indexed_ by a type from an inductive family. Here is an example:

```coq
Inductive Test1 : Type :=
  | T1 : Test1
with Test2 :=
  | T2 : Test2.

Inductive Test2_Prop : Test2 -> Prop :=
  | T2P : Test2_Prop T2.

QCDerive DecOpt for (Test2_Prop t2).
```

Before the patch, the `QCDerive` command fails and generates an ill-typed program:

```
In environment
t2_ : Test1
The term "t2_" has type "Test1" while it is expected to have type "Test2".
```

The bug is that it incorrectly assumes that the argument `t2` has type `Test1`. This patch fixes that and selects the correct inductive (in this case `Test2` from the inductive family).

It is explained in more detail in the original PR (https://github.com/QuickChick/QuickChick/pull/314):

> The computation derived in this example will be over an argument of the type Test1, whilst the correct type for t2 in the above example is Test2. The implementation as of now disregards that mutually inductive datatypes are essentially multiple definitions, and simply always considers the first definitions which is the type Test1 in the example.
> 
> My solution is more or less a copy from how constructors are handle, where an inductive relation can have multiple constructors, so the right one has to be targeted by means of an index. I applied the same idea for mutually inductive datatype definitions, and target the right one using an index. Then, the derivation of the DecOpt instance in the example, will have an argument with the type Test2 instead, and Coq will stop complaining because this computation now passes the type-check.

I could add this example to https://github.com/Xiving/QuickChick/blob/fix-deriving-mutual-inductive/test/plugin/plugin.v, but I don't think it's very enlightening.

**Comment by jaccokrijnen** [comment]
I've removed the reference to #65 , as this patch does not implement that.

**Pull request merged**
