### PR TITLE
avoid fmap pollution

### PR DESCRIPTION
**Pull request by liyishuai**
but broke some proofs

### CODE REVIEW

**Comment by Lysxia** [comment]
One problem with these classes is that they don't interact well with simplification tactics:

```
(* Goal: semGenSize (fmap f g) size <--> f @: semGenSize g size *)
simpl.
(* Goal: semGenSize (MkGen (fun (n : nat) (r : RandomSeed) => f (run g n r))) size <-->
  f @: semGenSize g size *)
```

That could be fixed  in ext-lib by marking `fmap` to not unfold (`Arguments ... nosimpl` or something) or making `Functor` a non-record class. But I'm also not convinced that's worth the trouble over having a plain `fmap` as it is now.

**Comment by liyishuai** [comment]
Then should we rename `fmap` to `fmapGen`?

**Comment by Lysxia** [comment]
I like haskell-hedgehog's way, which is to wrap all `Gen`-specific methods in a module `Gen` so you have to write `Gen.fmap`, which still allows you to import `Gen` in small enough scopes to use those names unqualified.

**Comment by Lysxia** [comment]
Could you also do this on 8.9 instead?

**Comment by liyishuai** [comment]
Merging is on my agenda. Now proposing on 8.8 for production concerns.

**Comment by liyishuai** [comment]
Call for experts in Coq modules -- my approach broke `Derive Arbitrary`.

**Pull request closed without merging**
