### PR TITLE
Adapt to https://github.com/coq/coq/pull/19530

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/19530
To be merged in sync with the upstream PR.

### CODE REVIEW

**Review by liyishuai — CHANGES_REQUESTED** [review]
Maybe worth moving these `Import` commands to `Compat.v.cppo`, to avoid preprocessing too many Coq files.

**Comment by Lysxia** [comment]
Is any of this not backwards compatible? The error comes from importing `WfExtensionality` which seems to be a mistake. Shouldn't the remaining imports work for existing versions of Coq?

**Comment by proux01** [comment]
Sorry, I always think of quickchick of a plugin (that usually in Coq CI have a specific brnach only compiling with Coq master) and forget about the .cppo thing. Done, this should now be backward compatible.
Still, please don't merge yet as this is not compatible with current master and should only be merged in sync with the upstream PR.

**Review by liyishuai — APPROVED** [review]

**Comment by proux01** [comment]
Upstream PR merged, please merge

**Comment by liyishuai** [comment]
The CI requires the coqorg/coq:dev Docker image to reflect the corresponding changes in Coq. When would that happen?

**Comment by proux01** [comment]
I don't know, whenever it will be rebuilt, maybe @erikmd could tell? It might be the case that this requires edit of some Docker config since the upstream PR adds an opam package.

**Comment by erikmd** [comment]
The coq/coq:dev is rebuilt automatically _after_ any merge in Coq master.
So, if the overlay is not backward compatible, you just need to wait for this merge + the build time (cf. the pipeline in gitlab.com/coq-community/docker-coq)

**Comment by erikmd** [comment]
FYI @liyishuai it appears you'll need to wait that [this problem](https://github.com/coq/coq/pull/19530#issuecomment-2524037317) is resolved
before retrying your build against coq dev.

**Comment by erikmd** [comment]
Good news @liyishuai, the coq.dev issue is fixed; so you can restart your CI build and/or merge this PR.

**Comment by proux01** [comment]
Thanks, CI green, please merge

**Pull request merged**
