### PR TITLE
[coq] Remove some more warnings, disable pervasive warning 8

### LINKED ISSUE #143: [warnings] Please fix OCaml warnings
Dear devs,

in Coq we are considering requiring plugins in the CI to use the same set of compiler flags for warnings than the main Coq tree (c.f. https://github.com/coq/coq/pull/9605 ), in particular, this means that the plugins should now compile warning-free, except for deprecation notices.

Note that some of the raised warnings are really fatal, [like missing match cases].

Please, try to fix OCaml warnings present in your codebase, thanks!

### PR DESCRIPTION
**Pull request by ejgallego**
This closes #143 and makes QuickChick compliant with
https://github.com/coq/coq/pull/9605

Can be merged without too many problems I think.

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks @liyishuai

**Comment by vbgl** [comment]
Could these changes be added to a new branch (say `8.10`) based on commit bf823751602407d0c9f8598c62e277ad5a5a8bcd? This could allow to have coq/coq#9605 in the version 8.10 of Coq.

Many thanks.

**Comment by liyishuai** [comment]
> Could these changes be added to a new branch (say `8.10`) based on commit [bf82375](https://github.com/QuickChick/QuickChick/commit/bf823751602407d0c9f8598c62e277ad5a5a8bcd)? This could allow to have [coq/coq#9605](https://github.com/coq/coq/pull/9605) in the version 8.10 of Coq.

We currently support Coq release 8.7~8.9 in the corresponding branches, and `coq.dev` in `master` branch. Are you in need of QuickChick with `coq.8.10.dev`?

**Comment by ejgallego** [comment]
Yup, 8.10 beta is around the corner so a branch for it should be created.

**Comment by liyishuai** [comment]
I have a [8.10](/liyishuai/QuickChick/tree/8.10) branch ready, modulo coq/opam-coq-archive#637

**Pull request merged**
