### PR TITLE
Upgrade simple-io

### PR DESCRIPTION
**Pull request by Lysxia**
I just fast-forwarded simple-io's `dev` to the current `master` which is getting stabilized. This is the associated changes.

### CODE REVIEW

**Comment by liyishuai** [comment]
So 8.8 branch should also track `coq-simple-io.dev`?

**Comment by Lysxia** [comment]
That's right.

**Comment by Lysxia** [comment]
Uh, wait.

**Comment by Lysxia** [comment]
Actually, no, it is better for 8.8 to point to officially released versions of dependencies, so this PR should target another branch.

**Comment by Lysxia** [comment]
Ugh, `coq-simple-io` now depends on `coq-ext-lib`. Do we need to update coq-opam-archive again?

**Comment by liyishuai** [comment]
Yes I'll do that.

**Pull request merged**
