### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by Lysxia**

### CODE REVIEW

**Comment by Lysxia** [comment]
The missing `_CoqProject` error was because the tutorial was being built in the wrong directory: it used to be in `examples/` and moved to `tutorials/`, but CI wasn't updated. Now I'm getting this exception on  the tutorial (on `Derive Checker`) and `ifc-basic` (on the command `Derive DecOpt`), and probably others (tried with Coq 8.15 and 8.16):

```
Uncaught exception Failure("FTB/2").
```

**Comment by Lysxia** [comment]
@lemonidas  Now I'm getting this exception:

```
File "./DerivingProofs.v", line 205, characters 0-34:
Error:
Anomaly
"Uncaught exception Failure("No Checkers or Producers for relation: eq")."
```

**Comment by lemonidas** [comment]
When they deprecated `pattern`, the type of hints available became opaque, which breaks the resolution of the derivation (QuickChick looks at the typeclasses hint table to figure out which instances exist in order to output appropriate code). I'm trying to think of a workaround.

**Comment by lemonidas** [comment]
Ok, I think I have a plan towards a solution going through the types of the constants hints are defined by, but it will take a couple of days to code and test.

**Pull request closed without merging**
