### PR TITLE
Fix mycppo script for Windows

### PR DESCRIPTION
**Pull request by Lysxia**
Don't use shebangs, call sh explicitly

cc @MSoegtropIMC

### CODE REVIEW

**Review by liyishuai — APPROVED** [review]

**Comment by MSoegtropIMC** [comment]
Did you already test this on Windows? If not I can do it.

**Comment by Lysxia** [comment]
I would be grateful if you can test it!

**Comment by MSoegtropIMC** [comment]
OK, I test it now.

**Comment by MSoegtropIMC** [comment]
@Lysxia : this patch appears to work (modulo things I accidentally fixed by making back merging errors ...). But I run into a different error now:
```
$ dune build -p coq-quickchick
Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
3.8 and will be removed in an upcoming Dune version.
Hint: To disable this warning, add the following to your dune-project file:
(warnings (deprecated_coq_lang_lt_08 disabled))
File "src/dune", line 1, characters 0-90:
1 | (coq.theory
2 |  (name QuickChick)
3 |  (package coq-quickchick)
4 |  (plugins coq-quickchick.plugin))
Error: No rule found for
T/bin/cygwin_cp_2/opam/CP.2024.01.0~8.19~2024.01+beta1/.opam-switch/build/coq-quickchick.2.0.3/_build/install/default/lib/coq-quickchick/META
File "src/dune", line 1, characters 0-90:
1 | (coq.theory
2 |  (name QuickChick)
3 |  (package coq-quickchick)
4 |  (plugins coq-quickchick.plugin))
Error: No rule found for
T/bin/cygwin_cp_2/opam/CP.2024.01.0~8.19~2024.01+beta1/.opam-switch/build/coq-quickchick.2.0.3/_build/install/default/lib/coq-quickchick/plugin/quickchick_plugin.cmxs
```
The path should be `T:/bin` not `T/bin`. I have no idea how the colon gets removed.

Everyting else seems to work - above is the complete output of a second dune run.

There is some discussion ongoing in Zulip (in the Coq Dev thread) on strange path effects of coqdep - possibly this is related, but the effect there is that I get a leading `../` in front of the `T:\`

**Comment by Lysxia** [comment]
It seems that dune is getting confused by paths, maybe because of something about cygwin, but I'm not sure why. I'll have a look myself within a week.

**Comment by MSoegtropIMC** [comment]
Note that dune is a MinGW exe - it doesn't know about cygwin. But if you call a shell the shell is a cygwin bash. The cygwin bash does properly handle absolute Windows paths with either / or \ and relative paths as long as paths are quoted.

The odd thing is that the path is missing a colon (it should be `E:/bin/`, not `E/bin/`. 8.19 coqdep does have isses with absolute Windows path, but the only case I have seen this manifests in a different way (it creates paths like `../E:/bin`.

In case you are using coqdep, it would be worthwhile to check the generated .Makefile.d file if it contains bogus paths. Otherwise we need to find out where the colon gets dropped.

**Comment by Lysxia** [comment]
I reduced it to a minimal test case and reported it on the Dune channel of the Coq Zulip:

```bash
# Usage: sh this-script
set -e
mkdir repro
cd repro
mkdir plugin
mkdir src
touch coq-quickchick.opam
cat > dune-project <<EOF
(lang dune 3.11)
(using coq 0.7)
(name coq-quickchick)
(version dev)
EOF
cat > plugin/dune <<EOF
(library
 (name quickchick_plugin)
(public_name coq-quickchick.plugin))
EOF
cat > src/dune << EOF
(coq.theory
 (name QC)
 (package coq-quickchick)
 (plugins coq-quickchick.plugin))
EOF
cat > src/QuickChick.v <<EOF
Declare ML Module "coq-quickchick.plugin".
EOF
dune build
```

**Pull request merged**
