### PR TITLE
Adapt to Coq PR11141

### PR DESCRIPTION
**Pull request by herbelin**
Hi, Coq [PR#11141](https://github.com/coq/coq/pull/11141) simplifies the organization of options to printing functions (including `extern_constr`) thanks to labels.

This QuickQuick PR is to adapt to the Coq PR (an argument to remove in `extern_constr`). Since QuickChick is tested in the Coq Continuous Integration, it should be merged synchronously with the Coq PR (the assignee is @ejgallego). Thanks!

### CODE REVIEW

**Comment by ejgallego** [comment]
@herbelin you need to adjust the base branch for this PR.

**Comment by ejgallego** [comment]
Upstream PR has been merged, please merge.

**Comment by liyishuai** [comment]
Merged despite Travis CI didn't pass. I'm discarding Travis and switching to CircleCI. The major concern is that `coqorg/coq:dev` is built nightly rather than realtime.
If the Coq Team prefers immediate merge to waiting for Docker image to update itself, I can upgrade Coq in CI instead.

**Comment by ejgallego** [comment]
Yup, the delay with docker images is indeed a problem; we are working on solving that problem.

**Pull request merged**
