### PR TITLE
[coq] Overlay for coq/coq#10419

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please merge now.

**Comment by ejgallego** [comment]
> CI without Dune complains about inconsistent assumption over `Decls`.

That's strange, are you caching some parts of the build directory? Maybe the Coq install directory is dirty?

**Comment by liyishuai** [comment]
I’m caching `.opam` directory. Latest Coq was installed via either `opam upgrade` (if a Coq exists) or `opam install --deps-only .`. Neither should introduce such inconsistency.

**Comment by ejgallego** [comment]
> Neither should introduce such inconsistency.

Unfortunately that can happen due to build system used for Coq's OPAM. Can you clean the cache and try again?

**Comment by liyishuai** [comment]
Restarted without cache.
Is the build issue Coq-specific or OPAM-generic? It’s not a "continuous" practice to clean cache every time.

**Comment by ejgallego** [comment]
> Restarted without cache.

It seems the build still used the cache, and indeed there is a stale `Decls` file.

> Is the build issue Coq-specific or OPAM-generic? It’s not a "continuous" practice to clean cache every time.

That's a problem of the two; `opam upgrade` plays bad with pinning [as to Coq dev] and the build system is not very smart. Actually cleaning up of stale files is a quite tricky business when doing incremental builds.

**Comment by SkySkimmer** [comment]
Could you merge and fix your CI independently?

**Comment by SkySkimmer** [comment]
Thanks

Gaëtan Gilbert

**Pull request merged**
