### PR TITLE
Adapt to coq/coq#11235 (Add syntax for non maximal implicit arguments)

### PR DESCRIPTION
**Pull request by SimonBoulier**

### CODE REVIEW

**Comment by herbelin** [comment]
Hi, coq/coq#11235 has just been merged, so this PR should now be merged so that QuickChick master remains synchronous with Coq master. Thanks in advance.

Note: I'm unsure to understand the effect of @liyishuai's force-push above, but I believe it is not merged yet since otherwise Coq could not be synchronous with QuickChick.

**Comment by ejgallego** [comment]
@liyishuai  ping

**Comment by liyishuai** [comment]
Any idea what caused this?
```
cd plugin/; sh plugin.sh
File "./plugin.v", line 11, characters 0-33:
Error: Argument mu0_ is a trailing implicit, so it can't be declared non
maximal. Please use { } instead of [ ].
```

**Comment by ejgallego** [comment]
> Any idea what caused this?

cc: @SimonBoulier @herbelin

**Comment by herbelin** [comment]
I suspect that `NonMaxImplicit` should rather be `MaxImplicit` in `src/genericLib.ml` in the PR. But I prefer @SimonBoulier confirms.

**Comment by SimonBoulier** [comment]
You seems right Hugo. Let's see what says the CI.

**Comment by SimonBoulier** [comment]
Why is dockercloud failing? Otherwise this seems good for me (`MaxImplicit` restores the old behavior).

**Comment by ejgallego** [comment]
Indeed @liyishuai this seems good to go I think.

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
