### PR TITLE
Adapt w.r.t. coq/coq#18940.

### PR DESCRIPTION
**Pull request by ppedrot**
I couldn't test this PR because for some weird reason the Coq CI script doesn't work locally for simple-io. Assuming it works it is backwards compatible.

### CODE REVIEW

**Comment by ppedrot** [comment]
So this doesn't work. I'll need a bit of help from the QuickChick devs to know how to fix this. In theory `auto using foo` behaves more or less the same as `pose foo; auto` (and similarly for the other auto-like tactics). It seems that this is not the case here, so some other solution should be sought.

**Comment by ppedrot** [comment]
Are you sure that the CI is working properly? This patch works locally for me, even for the `@cram` target.

**Comment by ppedrot** [comment]
For backwards compatibility, I ended up following another approach. I'm relying on the Ltac1 API that still uses constrs internally for now. It should be switched to the new Ltac2 API at some later point, except maybe if you want to add conditional compilation in TacticsUtil.

If you're fine with the changes, I think this is ready now.

**Review by liyishuai — APPROVED** [review]

**Comment by ppedrot** [comment]
Thanks!

**Pull request merged**
