### PR TITLE
Avoid looping instance resolution

### LINKED ISSUE #51: Unconstrained instance resolution loops
Here's a minimal example.

```
Require Import QuickChick.
Check arbitrary.
```

One workaround is to always pass arguments explicitly, but that doesn't take advantage of type classes, and it is prone to forgetful mistakes.

- I suppose Coq is repeatedly picking some blanket instances lying around. Wouldn't it be better to have them not in scope by default, or to reduce their priority to avoid these situations?

- What is the usual way out when Coq gets stuck like that? Currently in Proof General, I'm killing it (`C-x k *coq*`) but it's a chore to jump back in the previous location.

- Is Coq's instance resolution algorithm just a big backtracking search? Are there ways to customize it beyond priority numbers?

### PR DESCRIPTION
**Pull request by Lysxia**
Fixes #51.

Shall I also add this to `coq.8.6`?

### CODE REVIEW

**Comment by Lysxia** [comment]
For the record, another fix would be to add a `Gen` instance for a non-parametric type such as `nat`, which would have default priority `0`.

**Comment by liyishuai** [comment]
Does the argument `A` in `genOption` have to be explicit?

**Comment by Lysxia** [comment]
I'm not sure but I'll take that change out.

**Comment by liyishuai** [comment]
I think it's OK to apply this change to `coq.8.6` also, hopefully without breaking anything.

**Pull request merged**
