### PR TITLE
(CHEATING) Adapt to coq/coq#18422 (indirect accessor handled through vernactypes)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure we want to allow opaque access through tactics.

### CODE REVIEW

**Comment by ejgallego** [comment]
Upstream PR merged, please merge.

**Review by liyishuai — APPROVED** [review]

**Comment by liyishuai** [comment]
Blocked by the lack of SimpleIO that both (i) works with Coq 8.20 and (ii) is available via OPAM.

Slow path:
1. [ ] coq/opam#3010
2. [ ] Lysxia/coq-simple-io#66
3. Release another version of SimpleIO, and then merge here.

Fast, unsafe path: Merge now, fix OPAM later.

**Comment by Lysxia** [comment]
@liyishuai since I merged it in coq-simple-io master, the dev version should be enough right?

**Comment by liyishuai** [comment]
The dev version can't be installed in the CI environment:
- [ ] coq/opam#3011

**Pull request merged**
