### PR TITLE
Adapt to https://github.com/coq/coq/pull/19310

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/19310

This should be merged *only once upstream PR is merged*.

### CODE REVIEW

**Comment by proux01** [comment]
I'm a bit surprised to see CI green here, I would expect the test on Coq master to fail?

**Comment by liyishuai** [comment]
There are some parts missing in the CI, but my cache is outdated... Maybe an error could remind me of it.

**Comment by proux01** [comment]
Upstream PR merged, please merge

**Review by liyishuai — APPROVED** [review]

**Comment by proux01** [comment]
Thanks

**Pull request merged**
