### PR TITLE
More informative messages on unexpected failures

### LINKED ISSUE #246: Bad error when test artifact raises an exception
When a `QuickChick` command runs a program which raises an exception, we just see `Exited with status 2` which isn't very helpful. It would be nicer to report the exception as well.

Similarly, if the extracted code doesn't compile, would be nice to see the error message instead of digging in `build.log`.

### LINKED ISSUE #257: Report compiler errors to the user
When interfacing QC with untested OCaml code I often get errors like
```
Error:
Could not compile test program: /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/202430/QuickChickad4aab.ml
```

then I have to do something like
```
cd /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/202430/
dune build
```
to see the exact error (which almost all the time is just a typo) and then do `popd` to go to the project directory and fix the issue and build again and then repeat the cycle :)

I'd be much happier if I could see the compilation error right away.

### PR DESCRIPTION
**Pull request by Lysxia**
Closes #257 
Closes #246

### CODE REVIEW

**Comment by anton-trunov** [comment]
Very nice! :) Would you mind doing a new opam release after this PR is merged? We are actively building a project on QuickChick right now and this would be a huge help for us.

**Comment by anton-trunov** [comment]
Oh, actually I just tried this branch and it did not work for me, I see the following
```
Error:
Could not compile test program: /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/134015/QuickChickb4fea1.ml

Build log:



make: *** [test] Error 1
```

and 
```
cd /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/134015
dune build
```

shows something like this
```
File "extr/pretty.ml", line 5, characters 0-11:
5 | open PPrint
    ^^^^^^^^^^^
Error (warning 33): unused open PPrint.
File "extr/pretty.ml", line 6, characters 0-22:
6 | open PPrintCombinators
    ^^^^^^^^^^^^^^^^^^^^^^
Error (warning 33): unused open PPrintCombinators.
```

I'm using `QCInclude` and `QCDune` vernacular commands if that's relevant. I'm happy to provide more info if needed.

**Comment by Lysxia** [comment]
Thanks for testing! I'm guessing this error is getting printed to `stderr` (piped into `build.err`) so I should probably dump that as well.

**Comment by anton-trunov** [comment]
Awesome! This works and this is such a great improvement for my workflow :) Thanks a lot for your fix!

**Comment by Lysxia** [comment]
I'll cut a release over the weekend.

**Pull request merged**
