### PR TITLE
OPAM packaging and Travis integration

### PR DESCRIPTION
**Pull request by palmskog**
I'm interested in using QuickChick in one of my Coq 8.6 projects. The `trunk` branch seemed to be the most active, but the current Makefile there is very ad-hoc w.r.t. building and installation. I created two OPAM packages, one for the plugin and one for the mutation tool, that can be used to install/update/remove things as required in an OPAM-based setting like mine. To demonstrate that they work as expected, I activated Travis in my fork and added Travis scripts.

### CODE REVIEW

**Comment by lemonidas** [comment]
Thanks for this! We're still in the middle of a lot of development in trunk, and we were planning on creating an OPAM package _real soon now_. I'll look into this once the craziness dies down a bit.

**Comment by palmskog** [comment]
@lemonidas That's fine if you merge at some later point, this was mainly for me to be able to try out QuickChick conveniently. For the record, the main inconvenience right now (which the `install` files work around) is arguably the handling of `quickChickLib` - one solution might be to package that up separately and use `ocamlfind -package <pkgname>` instead of raw `ocamlopt` in `quickChick.ml4`.

**Comment by Lysxia** [comment]
Hi! What's the status on opam packaging for QuickChick now?

**Comment by liyishuai** [comment]
@Lysxia We now have `opam` file in our repository, which works for `coq.8.6` branch. It has not yet been published to OPAM Archive. We might also need to update `opam` to support `master` branch.

**Comment by palmskog** [comment]
Until the OPAM file is published to some archive, I would recommend going to the QuickChick directory and running: `opam pin add .`

This will use the local directory as source of the package (rather than the github repo itself), but it's a lot more convenient than `make install`, which doesn't have an uninstallation option.

Closing this PR.

**Pull request closed without merging**
